Delegateパターンを用いてUseCaseを書き換えました
Reon0429-cat/ios-training pull request #10
Opened 2022-05-13 01:34 UTC by Reon0429-cat

# 概要
[session10](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Delegate.md)

# やったこと
`WeatherUseCase`をクロージャで実装していたものをDelegateパターンを用いて書き換えました。
`WeatherDisplayViewController`で`deinit`メソッドをかき、このメソッドが呼ばれていることを確認しました。

# 動作
iPhone13 Pro
https://user-images.githubusercontent.com/66917548/168193733-98dffdfe-28bd-474a-8f5f-edeac5e642e1.mp4

# 気になること
特にありません

# 備考
特にありません

2022-05-13 14:11 UTC, ykws requested changes
テストケースも Delegate を利用した変更を試してみてください。

2022-05-13 14:11 UTC, ykws commented on ios-training/UseCases/WeatherUseCase.swift
> +    func execute(result: Result<Weather, Error>)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Delegate のメソッドはその処理が開始したり、完了した時に呼ばれるので、命名もそれに沿っていると驚きが少ないです。 `execute` だと実行するになってしまいますが、今回のケースだと**天気予報の取得が完了した**時になると思います。
以下、 Apple の命名も参考に、他にも Delegate で調べてみて適切な名前を考えてみてください。

- [UIApplicationDelegate](https://developer.apple.com/documentation/uikit/uiapplicationdelegate)
- [CLLocationManagerDelegate](https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate)

また上記を見てもらうと Delegate では成功とエラーは別々の出口を用意し、通知することが多いです。
これは受け手が成功とエラーで異なる処理を行うケースが多く、本アプリでもその方が嬉しいはずです。

2022-05-16 00:30 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +    func execute(result: Result<Weather, Error>)
> テストケースも Delegate を利用した変更を試してみてください。
> Delegate のメソッドはその処理が開始したり、完了した時に呼ばれるので、命名もそれに沿っていると驚きが少ないです。 execute だと実行するになってしまいますが、今回のケースだと天気予報の取得が完了した時になると思います。
> 以下、 Apple の命名も参考に、他にも Delegate で調べてみて適切な名前を考えてみてください。

ありがとうございます！こちらに関しまして、https://github.com/Reon0429-cat/ios-training/pull/10/commits/0050cc761c92eeb4db474e4caf51dca7583d4684　で対応済みなのですが、うまく反映されていませんでしょうか？

> また上記を見てもらうと Delegate では成功とエラーは別々の出口を用意し、通知することが多いです。
> これは受け手が成功とエラーで異なる処理を行うケースが多く、本アプリでもその方が嬉しいはずです。

修正します！

2022-05-16 01:25 UTC, Reon0429-cat commented
コンフリクト解消DONE

2022-05-16 01:35 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +    func execute(result: Result<Weather, Error>)
@ykws 

> また上記を見てもらうと Delegate では成功とエラーは別々の出口を用意し、通知することが多いです。
> これは受け手が成功とエラーで異なる処理を行うケースが多く、本アプリでもその方が嬉しいはずです。


こちら修正させていただきました。(https://github.com/Reon0429-cat/ios-training/pull/10/commits/9153fd3fda6beadd4b21adeab7db5f7ddf9e41d7)

2022-05-16 04:14 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/130609)

2022-05-24 05:02 UTC, ykws approved these changes
![LGTM](https://image.lgtmoon.dev/114862)

2022-05-24 05:02 UTC, ykws commented on ios-training/UseCases/WeatherUseCase.swift
>  protocol WeatherUseCaseProtocol {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

```suggestion
protocol WeatherUseCaseProtocol: AnyObject {
```

2022-05-24 05:02 UTC, ykws commented on ios-training/UseCases/WeatherUseCase.swift
>  protocol WeatherUseCaseProtocol {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Protocol として Delegate の実装を強制しておくと実装漏れを防げるようにしておくとより安心です。

2022-05-24 05:23 UTC, merged