コンカレンシーを用いてWeatherUseCaseを書き換えました
Reon0429-cat/ios-training pull request #12
Opened 2022-05-16 04:22 UTC by Reon0429-cat

# 概要
[session12](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Concurrency.md)

# やったこと
WeatherUseCaseをasync/awaitを用いて書き換えました。

# 動作
iPhone13 Pro

2022-05-16 04:35 UTC, Reon0429-cat commented
バグが二点修正できませんので、アドバイスいただきたいです。

# バグ1 `UIActivityIndicator`が表示されない
リロードボタンタップ後に天気を再度フェッチするときにインジケーターが表示されません。
クローズボタンタップ後に再度`WeatherDisplayViewController`を表示するときはインジケーターは表示されてくれます。
それぞれのボタンで呼び出しているメソッドは`displayWeather()`で共通なのでなぜこのようになってしまうのかわからず、解決できませんでした。

# バグ2 `willEnterForegroundNotification`が通知されたときにアプリが落ちる
アプリを一度バックグラウンドにし、フォアグラウンドに戻すとアプリが落ちてしまい、`Thread 1: EXC_BAD_ACCESS (code=2, address=0x14f504080)`と表示されてしまいます。メインスレッドが原因で落ちてしまうことまでは分かりましたが、解決できませんでした。

2022-05-16 10:18 UTC, Reon0429-cat commented
## バグ3 `deinit`が呼ばれない
`WeatherDisplayViewController`の`deinit`が呼ばれてくれません。`viewDidLoad`の
```
Task {
    await self.addObserverWillEnterForegroundNotification()
}
```
をコメントアウトすると`deinit`が呼ばれるため、この部分に原因があると思われます。

2022-05-17 15:38 UTC, ykws requested changes
コメントした箇所の確認をお願いします。

それと、
#2 からだと思いますが、以下のエラーのため、 storyboard で設定している初期画像が表示できていなかったようです。

```
Could not load the "Rainy" image referenced from a nib in the bundle with identifier "reon.oonishi.ios-training"
```

初回ロード前に表示されない方が良いので、 storyboard の設定を直す（正しくは `rainy` 小文字始まり）のと、必要に応じて、初回ロード前に画像の初期化をすると良いです。

2022-05-17 15:38 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        Task {
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

Task で囲うのは最小限にできればと思います。
addObserverWillEnterForegroundNotification はどうして async なのでしょうか？

2022-05-17 15:38 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                await strongSelf.displayWeather()
![must-badge](https://img.shields.io/badge/review-must-red.svg)

こう書くとアラートを表示した状態で addObserver したタイミング L.76 で、天気予報が更新されていますね。
アラートを表示している場合に更新しないのは煩雑なので、アラートを閉じて天気予報を更新してしまっても良いと思います。

https://github.com/Reon0429-cat/ios-training/pull/7#discussion_r870348849

2022-05-17 15:38 UTC, ykws commented on ios-trainingTests/ios_trainingTests.swift
> +            XCTAssertEqual(image, UIImage(named: "sunny"))
![must-badge](https://img.shields.io/badge/review-must-red.svg)

この書き方だと Assert が実行されずにテストパスしているように見えるだけなので見直しをお願いします。
"sunny" を "rainy" に書き換えたり、ブレイクポイントを設定してテストを実行して確認できます。

2022-05-17 15:38 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        Task {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Task で囲うのは最小限にできればと思うので、 displayWeather の中で必要な箇所だけ囲んでみましょうか

2022-05-17 15:38 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +    @objc private func displayWeather() async {
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

ここの async は必要でしょうか？
Task の見直しと合わせて確認してみてください。

2022-05-17 15:38 UTC, ykws commented on ios-training/UseCases/WeatherUseCase.swift
> +        let task: Task<Weather, Error> = Task.detached {
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

Task.detached はどういう意図で利用していますか？
func に async を付与しているので、  L.69 `return weather` で十分かと思いました。

2022-05-17 15:38 UTC, ykws commented on ios-training/UseCases/WeatherUseCase.swift
> +        return try await task.value
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

これが L.57 asyncFetchWeather の前に返りますね。

2022-05-18 01:38 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        Task {
すみません、バグを修正して調査している間に不要になったことに気づかず、つけたままにしてしまっていました！

2022-05-18 01:53 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +        let task: Task<Weather, Error> = Task.detached {
すみません、こちらもバグを修正して調査している間に不要になったことに気づかず、つけたままにしてしまっていました！

2022-05-18 03:36 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                await strongSelf.displayWeather()
> コメントした箇所の確認をお願いします。
> 
> それと、 #2 からだと思いますが、以下のエラーのため、 storyboard で設定している初期画像が表示できていなかったようです。
> 
> ```
> Could not load the "Rainy" image referenced from a nib in the bundle with identifier "reon.oonishi.ios-training"
> ```
> 
> 初回ロード前に表示されない方が良いので、 storyboard の設定を直す（正しくは `rainy` 小文字始まり）のと、必要に応じて、初回ロード前に画像の初期化をすると良いです。

修正しました！(https://github.com/Reon0429-cat/ios-training/pull/12/commits/385406d9040b50128ab52d9f9fa73d666037e8fe)

2022-05-18 03:37 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        Task {
修正できました！(https://github.com/Reon0429-cat/ios-training/pull/12/commits/2d9e64d3a437d31434aa5880b4bc1d8e4623ec74)

2022-05-18 03:38 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +    @objc private func displayWeather() async {
修正しました！(https://github.com/Reon0429-cat/ios-training/pull/12/commits/0cb4e76234860ef577e01524517088ec7787b1be)

2022-05-18 03:39 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +        let task: Task<Weather, Error> = Task.detached {
修正しました！(https://github.com/Reon0429-cat/ios-training/pull/12/commits/2555e00a5bf3672537d3f91d15f0d8eb1d5e19a4)

2022-05-18 03:41 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                await strongSelf.displayWeather()
> こう書くとアラートを表示した状態で addObserver したタイミング L.76 で、天気予報が更新されていますね。
> アラートを表示している場合に更新しないのは煩雑なので、アラートを閉じて天気予報を更新してしまっても良いと思います。

すみません、アラートを閉じる処理が実行されず、113行目のalertがnilになってしまい、原因がわからなかったのでアドバイスいただきたいです。

https://github.com/Reon0429-cat/ios-training/pull/12/commits/3fe8853bf82fd3758e6434d0c9b5e3c56719b851

2022-05-18 03:43 UTC, Reon0429-cat commented on ios-trainingTests/ios_trainingTests.swift
> +            XCTAssertEqual(image, UIImage(named: "sunny"))
`XCTAssertEqual`が`ViewController`の初期化処理の前に実行されてしまい、テストが通らないのですが、初期化処理を行なったとにテストを実行する方法はありますでしょうか？

https://github.com/Reon0429-cat/ios-training/pull/12/commits/ee47a26c7f9fa6312dd88ee26c14b494661403dc

2022-05-18 09:16 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                await strongSelf.displayWeather()
アラートを表示した状態で addObserver したタイミング で天気予報が更新されないようにしました！

2022-05-24 05:15 UTC, ykws requested changes

2022-05-24 05:15 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +            guard let strongSelf = self else { return }
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

https://github.com/Reon0429-cat/ios-training-bugfix/pull/8#discussion_r878982400

2022-05-24 05:15 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +    private func closeErrorAlertIfNeeded() {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Error の文脈がここでは扱われていないので closeAlertIfNeeded でも良さそうです。

2022-05-24 05:15 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
>                  DispatchQueue.executeMainThread {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

await を利用することによって、プログラムから DispatchQueue が不要になっているはずなので確認してみてください

2022-05-24 05:15 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +            alert.dismiss(animated: true)
![must-badge](https://img.shields.io/badge/review-must-red.svg)

バックグラウンド復帰で閉じれなくなっているようなので確認をお願いします。

2022-05-25 04:26 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
>                  DispatchQueue.executeMainThread {
awaitの後はメインスレッドに戻るようなので不要ですね！

2022-05-25 05:13 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +            alert.dismiss(animated: true)
修正できました！
https://github.com/Reon0429-cat/ios-training/pull/12/commits/d5de12e60fe5d16bf3c69181f8db339a8c87899b

2022-05-26 03:31 UTC, novr commented on ios-training/Interfaces/AlertPresentable.swift
> +    func presentErrorAlert(
[IMO] handlerでUIAlertControllerを取得させる必要がなさそうです
```suggestion
    @discardableResult
    func presentErrorAlert(title: String, actionHandler: ((UIAlertAction) -> Void)? = nil) -> UIAlertController
```
```suggestion
    func presentErrorAlert(
```

2022-05-26 03:31 UTC, novr commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                            self.addObserverWillEnterForegroundNotification()
[MUST] alertControllerをフィールドに保持するのでselfにweakかalertControllerにweakが必要です

2022-05-26 03:31 UTC, novr commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                            self.addObserverWillEnterForegroundNotification()
[MUST] alertControllerをフィールドに保持するのでselfにweakかalertControllerにweakが必要です

2022-05-26 04:22 UTC, Reon0429-cat commented on ios-training/Interfaces/AlertPresentable.swift
> +    func presentErrorAlert(
修正させていただきました！
https://github.com/Reon0429-cat/ios-training/pull/12/commits/ecd134cb2e97919afaaf6d660b0604cd4be42655

2022-05-26 04:23 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                            self.addObserverWillEnterForegroundNotification()
修正させていただきました！

2022-05-27 11:56 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
>                  DispatchQueue.executeMainThread {
✅ 62fe253685b9d6da789059b314e225ddc1642de5

2022-05-27 12:12 UTC, ykws requested changes

2022-05-27 12:12 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
>                  DispatchQueue.executeMainThread {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

こちらも確認をお願いします。

https://github.com/Reon0429-cat/ios-training/pull/12#discussion_r880062459

2022-05-27 12:12 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        NotificationCenter.default.addObserver(forName: UIApplication.willEnterForegroundNotification,
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

ここを変更している理由は何になりますか？

2022-05-27 12:12 UTC, ykws commented on ios-trainingTests/ios_trainingTests.swift
> +            XCTAssertEqual(image, UIImage(named: "sunny"))
テスト通っているように見えましたが、そちらの環境だとパスしないですか？

2022-05-27 12:58 UTC, auramagi requested changes

2022-05-27 12:58 UTC, auramagi commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        super.loadView()
loadViewはsuperの呼び出しが禁止されています。
> Your custom implementation of this method should not call super.
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview

```suggestion
```

2022-05-27 12:58 UTC, auramagi commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
>                  DispatchQueue.executeMainThread {
(修正箇所外の指摘ですみません）
UIViewController のサブクラスは MainActor になっているのでその中のプロパティへのアクセス・関数内の処理はメインスレッドに行なわれることが保証されています。`Task { }` でコンカレンシーを開始したら暗黙的にこのコンテキストを維持するので、その中身もメインスレッドになります。なので今現在の使用では、別途メインスレッドに移譲する必要がありません。

メインスレッドじゃないコンカレンシーを開始したい場合は、`Task.detached { }` と書きましょう。その場合はメインスレッドに戻って処理をするときは `MainActor.run { }` が使えて DispatchQueue の必要がありません。

2022-05-27 12:58 UTC, auramagi commented on ios-training/UseCases/WeatherUseCase.swift
> +        }
そのまま re-throw するだけなので、doブロックが不要そう

2022-05-31 05:16 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        NotificationCenter.default.addObserver(forName: UIApplication.willEnterForegroundNotification,
すみません、コンフリクトを直してる時に使わない方を残してしまったみたいです。

2022-05-31 05:23 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
>                  DispatchQueue.executeMainThread {
ありがとうございます！イメージが湧きました！コンカレンシーを使っているときはDispatchQueueを書く必要がないまたは別の記述方法で書蹴ることに気をつけたいと思います！

2022-05-31 05:27 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +        }
修正させていただきました！
https://github.com/Reon0429-cat/ios-training/pull/12/commits/17d433a84649ec148be2aa91f871fb464b3033bc

2022-05-31 05:27 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        super.loadView()
修正させていただきました！
https://github.com/Reon0429-cat/ios-training/pull/12/commits/ab1fd245ee40e25799bbfd90452401152fc3b8fe

2022-05-31 05:29 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
>                  DispatchQueue.executeMainThread {
こちらのいただいた[コメント](https://github.com/Reon0429-cat/ios-training/pull/12#discussion_r883589442)と合わせて確認し、メインで実行されるのが理解できたので削除して修正させていただきました！
https://github.com/Reon0429-cat/ios-training/pull/12/commits/ab26a61a91847b2b45e6f5549cb63f9c64991b95

2022-05-31 06:03 UTC, Reon0429-cat commented on ios-trainingTests/ios_trainingTests.swift
> +            XCTAssertEqual(image, UIImage(named: "sunny"))
以前のsessionで改善点を教えていただいたので、そこでこちらも修正できましたので、こちらのコメントは解決済みですね！

2022-05-31 10:02 UTC, auramagi approved these changes
私からのコメントは解消されたので approve します。
![LGTM](https://i.lgtm.fun/1lk7.png)

2022-05-31 22:10 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/79359)

2022-06-01 07:44 UTC, ykws approved these changes
Swift Concurrency のおかげで DispatchQueue を意識しないで済むようになって Good です！

![LGTM](https://image.lgtmoon.dev/7525)

2022-06-01 08:27 UTC, merged