テーブルに天気のリストを表示させ、下に引っ張るとリフレッシュされるように実装しました。
Reon0429-cat/ios-training pull request #13
Opened 2022-05-17 06:37 UTC by Reon0429-cat

# 概要
[session13](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/UITableView.md)

# やったこと
`YumemiWeather.asyncFetchWeatherList()`に変更し、テーブルセルに最高気温、最低気温、エリア、天気アイコンを表示させ、テーブルを下にスクロールすると再度天気が取得されるようにしました。

# 動作
iPhone13 Pro
https://user-images.githubusercontent.com/66917548/168744566-ca3930b8-32d4-45a7-b06b-b2e20880fbf5.mp4

# 気になること
特にありません

# 備考
特にありません

2022-05-17 14:43 UTC, ykws reviewed
テストコードの方も確認してみてください。

2022-05-17 14:43 UTC, ykws commented on ios-training/UseCases/WeatherUseCase.swift
> +            let weatherRequest = WeatherRequest(areas: ["Tokyo"], date: Date())
折角なので Tokyo 以外の都市もリストで渡してリスト表示してみましょうか

2022-05-17 14:43 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> -            await self.displayWeather()
詳細画面で Reload できる状態で良いと思いました。

このコミットの粒度が大きいのでリスト表示と詳細表示の変更は分割できると良いと思いました。

2022-05-18 07:10 UTC, Reon0429-cat commented
コンフリクト修正します

2022-05-18 08:37 UTC, Reon0429-cat commented
コンフリクト解消DONE

2022-05-18 08:37 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> -            await self.displayWeather()
修正しました！

2022-05-18 08:38 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +            let weatherRequest = WeatherRequest(areas: ["Tokyo"], date: Date())
ランダムな都市で表示できるように変更しました！

2022-05-18 08:39 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +            let weatherRequest = WeatherRequest(areas: ["Tokyo"], date: Date())
https://user-images.githubusercontent.com/66917548/168996280-de3dea12-ca06-4ed0-a3a6-0d3c1624f812.mp4

2022-05-19 02:26 UTC, ykws commented on ios-training/UseCases/WeatherUseCase.swift
> +            let weatherRequest = WeatherRequest(areas: ["Tokyo"], date: Date())
結果がリストで取得できるので、例えばですが、次のようなリスト `["Tokyo", "Osaka", "Nagoya", "Kyoto"]` でリクエストして、現状の1件表示ではなく、以下のようにリスト表示できればと思いました。

- Tokyo
- Osaka
- Nagoya
- Kyoto

2022-05-19 06:53 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +            let weatherRequest = WeatherRequest(areas: ["Tokyo"], date: Date())
あ、すみません、勘違いしてしまいました！

2022-05-19 06:56 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +            let weatherRequest = WeatherRequest(areas: ["Tokyo"], date: Date())
修正させていただきました!
https://github.com/Reon0429-cat/ios-training/pull/13/commits/e584d57358f0d48ae0a70a6ccbe6ee1cd1853100

2022-05-26 04:02 UTC, novr requested changes
ModelがいないのでFatVCの傾向があります

2022-05-26 04:02 UTC, novr commented on ios-training/WeatherList/WeatherTableViewCell.swift
> +    func configure(with weather: (weather: Weather, area: String)) {
[IMO] `area: String`不要では？

2022-05-26 04:02 UTC, novr commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                guard let weather = weatherItems.map({ $0.info }).randomElement() else {
[MUST] 不要なデータを取得しています
1件取得用のAPIを使いましょう

また、mapしてからrandomElementするのは不要な処理が行われます
使われるのは1要素なので他要素の変換は不要なはず

2022-05-26 04:02 UTC, novr commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                    self.setupUI(weather: weather)
[IMO] 呼び出すメソッドの名前が適切ではないです
`setupUI`であれば初期化時に行われ、再利用されるべきではないです

2022-05-27 01:35 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                    self.setupUI(weather: weather)
修正させていただきました！https://github.com/Reon0429-cat/ios-training/pull/13/commits/0aa26e3ab8330cd09db46630e315a31470aabba4

2022-05-27 01:36 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                guard let weather = weatherItems.map({ $0.info }).randomElement() else {
修正させていただきました！
https://github.com/Reon0429-cat/ios-training/pull/13/commits/ae09ab06f68ecb4e6c12c32b613e7ddff661dd90

2022-05-27 01:36 UTC, Reon0429-cat commented on ios-training/WeatherList/WeatherTableViewCell.swift
> +    func configure(with weather: (weather: Weather, area: String)) {
修正させていただきました！https://github.com/Reon0429-cat/ios-training/pull/13/commits/90075386068dfd1c09a2441c82cf3af5e4ec125f

2022-05-27 01:47 UTC, Reon0429-cat commented
コンフリクトを修正しました

2022-05-27 13:49 UTC, ykws requested changes

2022-05-27 13:49 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                DispatchQueue.executeMainThread {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

https://github.com/Reon0429-cat/ios-training/pull/12#discussion_r880062459

2022-05-27 13:49 UTC, ykws commented on ios-training/WeatherList/WeatherListViewController.swift
> +                DispatchQueue.executeMainThread {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

https://github.com/Reon0429-cat/ios-training/pull/12#discussion_r883549249

2022-05-27 13:49 UTC, ykws commented on ios-training/WeatherList/WeatherTableViewCell.swift
> +private extension Weather {
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

WeatherDisplayViewController にも同じ extension がありますが、あえて分けていますか？

2022-05-27 13:49 UTC, ykws commented on ios-trainingTests/WeatherUseCaseStub.swift
> -    func fetchWeather() async throws -> Weather {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

こちらも必要なはず。
テストでコンパイルエラーになるので確認をお願いします。

2022-05-27 13:49 UTC, ykws commented on ios-training/UseCases/WeatherUseCase.swift
> +        guard let area = Area.allCases.randomElement()?.rawValue else {
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

今回の変更で fetchWeather を呼ぶ時は一意に area が特定されると思うので、受け取ってリスクエストできそうでしょうか？

2022-05-27 13:49 UTC, ykws commented on ios-training/WeatherDisplay/Base.lproj/WeatherDisplay.storyboard
> -                                    <constraint firstAttribute="width" constant="30" id="Fwz-dy-pr2"/>
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

今回の変更だと WeatherDisplay のレイアウトには変更が入っていない想定ですが、 制約を消されましたか？
意図しない変更差分であれば、元に戻してコミットしてもらえればと思います。

### 変更前のコードに戻すコマンドの一例

```
$ git checkout main ios-training/WeatherDisplay/Base.lproj/WeatherDisplay.storyboard
```

2022-05-27 13:49 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> -    override func viewWillAppear(_ animated: Bool) {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

Close して再表示の挙動がなくなっているので viewWillAppear で実行しなくて良くなってる

2022-05-31 05:58 UTC, Reon0429-cat commented on ios-training/WeatherList/WeatherTableViewCell.swift
> +private extension Weather {
ViewControllerが違うのでそれぞれ分けてあえて二個書いたのですが、天気が増えた時や画像の名前を変えた時などどっちの変更しないといけないので手間になりそうですね。
この場合はWeather+Extensionとかってファイルを作ってそこに一つ書いてそれぞれのViewで使うという感じで良いでしょうか？

2022-05-31 06:26 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +                DispatchQueue.executeMainThread {
https://github.com/Reon0429-cat/ios-training/pull/13/commits/8d8595946084021e8c3ad33ec57093e6a9ef857a

2022-05-31 06:26 UTC, Reon0429-cat commented on ios-training/WeatherList/WeatherListViewController.swift
> +                DispatchQueue.executeMainThread {
修正させていただきました！
https://github.com/Reon0429-cat/ios-training/pull/13/commits/8d8595946084021e8c3ad33ec57093e6a9ef857a
https://github.com/Reon0429-cat/ios-training/pull/13/commits/73a3d4e3440aefb885d6b1af15f2f8f6833d3c48

2022-05-31 06:27 UTC, Reon0429-cat commented on ios-trainingTests/WeatherUseCaseStub.swift
> -    func fetchWeather() async throws -> Weather {
修正させていただきましtあ！
https://github.com/Reon0429-cat/ios-training/pull/13/commits/4b587969a545f680ead96eac8f2137516cda409d

2022-05-31 06:28 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +        guard let area = Area.allCases.randomElement()?.rawValue else {
Weatherを渡していたところをWeatherItemを渡すように変更し、fetchWeatherでareaにアクセスできるようにすることで修正させていただきました！
https://github.com/Reon0429-cat/ios-training/pull/13/commits/86e5a90b1bfb9fd822b1cc21ba464657621fea50

2022-05-31 06:30 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/Base.lproj/WeatherDisplay.storyboard
> -                                    <constraint firstAttribute="width" constant="30" id="Fwz-dy-pr2"/>
こちら修正させていただいたのですが、こちらのコマンドがいまいち理解できませんでした。
https://github.com/Reon0429-cat/ios-training/pull/13/commits/155b294118e9d00ea01aa76d44529a5c2447a6f4

git checkout A BでAブランチに移動後にそのブランチのBファイルの変更を無くすという理解でよろしいでしょうか？

2022-06-02 14:38 UTC, ykws requested changes

2022-06-02 14:38 UTC, ykws commented on ios-trainingTests/ios_trainingTests.swift
> +            weatherItem: weatherItem,
weatherItem の方で天気を表示するようになっているので、 weatherUseCase をテストする経路がなくなっているんですよね。

2022-06-02 14:38 UTC, ykws commented on ios-trainingTests/ios_trainingTests.swift
> +        let weatherUseCaseStub = WeatherUseCaseStub(weatherItem: weatherItem)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

area 固定なので、変更前と同じ weather を渡して、 WeatherUseCaseStub 生成時に WeatherItem を生成するでも良さそうです。

```suggestion
    private func setupWeatherDisplay(weather: Weather) {
        let weatherItem = WeatherItem(info: weather, area: "Tokyo")
        let weatherUseCaseStub = WeatherUseCaseStub(weatherItem: weatherItem)
```

2022-06-02 14:38 UTC, ykws commented on ios-training/UseCases/WeatherUseCase.swift
> +        let fetchedJson = try await YumemiWeather.asyncFetchWeather(jsonString)
![must-badge](https://img.shields.io/badge/review-must-red.svg)

List ver を使用していないので必ず「予期しないエラーが発生しました。」と表示されています。

<img width="240" alt="Simulator Screen Shot - iPhone 13 - 2022-06-02 at 23 33 31" src="https://user-images.githubusercontent.com/5770480/171653795-2d7118e4-0994-4822-a7b8-208dba2dea99.png">

2022-06-03 01:48 UTC, Reon0429-cat commented on ios-trainingTests/ios_trainingTests.swift
> +        let weatherUseCaseStub = WeatherUseCaseStub(weatherItem: weatherItem)
@ykws area固定とは、areaを何か一つのものに固定してテストをするということでしょうか？WeatherList画面のタップされたareaという意味ではなくでしょうか

2022-06-03 01:55 UTC, Reon0429-cat commented on ios-trainingTests/ios_trainingTests.swift
> +        let weatherUseCaseStub = WeatherUseCaseStub(weatherItem: weatherItem)
すみません、理解できました！

2022-06-08 02:45 UTC, yumemi-skino commented on ios-training/UseCases/WeatherUseCase.swift
> +        let fetchedJson = try await YumemiWeather.asyncFetchWeather(jsonString)
@Reon0429-cat APIは↓とかですかねー
https://yumemi-inc.github.io/ios-training/documentation/yumemiweather/yumemiweather/asyncfetchweatherlist(_:)

2022-06-08 03:02 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +        let fetchedJson = try await YumemiWeather.asyncFetchWeather(jsonString)
すみません、プッシュしてなかったです！

2022-06-08 03:03 UTC, Reon0429-cat commented on ios-training/UseCases/WeatherUseCase.swift
> +        let fetchedJson = try await YumemiWeather.asyncFetchWeather(jsonString)
https://github.com/Reon0429-cat/ios-training/pull/13/commits/e74755c9c2381af33726f90a72de1ec713363639

2022-06-08 03:46 UTC, yumemi-skino approved these changes
LGTMです！！

2022-06-08 03:46 UTC, yumemi-skino commented on ios-training/WeatherList/WeatherListViewController.swift
> +        refreshControl.endRefreshing()
[感想]
とくに修正の必要はありませんが、
UIとしてはリフレッシュが完了するまでの間はrefreshControlが表示されたままの方が良さそうと思いました
また、画面が表示された時に開始するfetch中にもリフレッシュが可能なようです（fetch処理の重複）
このあたりを解決するには状態管理が必要そうですね

2022-06-08 04:50 UTC, Reon0429-cat commented on ios-training/WeatherList/WeatherListViewController.swift
> +        refreshControl.endRefreshing()
ありがとうございます！その観点はなかったので、今度からはそこ辺りも意識してみます！

2022-06-08 12:03 UTC, ykws approved these changes
リスト表示できることを確認できました！

![LGTM](https://image.lgtmoon.dev/132917)

2022-06-09 01:24 UTC, merged