リロードボタンタップ時に天気画像を再読み込みさせました。
Reon0429-cat/ios-training pull request #2
Opened 2022-04-22 05:59 UTC by Reon0429-cat

- 概要
[session2](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/API.md)
リロードボタンをタップしたときに、天気の情報を再度取得し、UIImageViewにカラーを変更して反映させました。

- やったこと
今後、晴れ、雨、曇り以外の天気が増えることを想定し、Weatherファイルにそれぞれモデルを定義しておきました。
WeatherPresenterクラスを作り、コントローラー側でYumemiWeatherAPIを意識しないようにしました。
テストコードを書くことを想定し、WeatherDisplayViewControllerでWeatherUseCaseをDIさせることにしました。

- 気になること
1. WeatherファイルにUIKitをSunnyモデルなどでUIColorを使いたい都合、importしてしまっていること。

- 質問
1. 「気になること」の改善案がありましたらお聞きしたいです。
2. 全体的に命名規則に不安があります。

- 備考
各クラスの責務があやふやなので、そこあたりも見ていただきたいです。

2022-04-22 06:21 UTC, novr requested changes

2022-04-22 06:21 UTC, novr commented on ios-training/Assets.xcassets/cloudy.imageset/Contents.json
> +      "filename" : "iconmonstr-weather-11.pdf",
PDFの場合はsingle scaleでpreserve vector data にチェックを入れましょう
![image](https://user-images.githubusercontent.com/47618299/164614473-806b750d-0385-49d0-90e8-a06935e3f478.png)

2022-04-22 06:21 UTC, novr commented on ios-training/Weather.swift
> +}
全て固定値の表現ならばinstanceを作る必要がないので、enumではどうでしょう

2022-04-22 06:55 UTC, ykws requested changes
アーキテクチャの適用には、今の要件には、どんな責務があって、それを分割した時に、この責務はこのクラスに、という風に役割分担を決めると書きやすいと思いました。
現段階では、要件は比較的シンプルなので、責務の数も少なくて、必然的に必要なクラスも少なくできるのでは、という観点を持ってもらっても良いかもと思いました。

2022-04-22 06:55 UTC, ykws commented on ios-training/Assets.xcassets/cloudy.imageset/Contents.json
> +      "scale" : "3x"
![must-badge](https://img.shields.io/badge/review-must-red.svg)

Vector Data として Single Scale できれいに表示できます。

<img width="763" alt="156695732-78cae9da-0788-47da-8c78-03f8b8810665" src="https://user-images.githubusercontent.com/5770480/164615623-3003a199-0255-415b-9acc-03e7b962cb52.png">

2022-04-22 06:55 UTC, ykws commented on ios-training/Assets.xcassets/cloudy.imageset/Contents.json
> +      "scale" : "3x"
```suggestion
```

2022-04-22 06:55 UTC, ykws commented on ios-training/Assets.xcassets/rainy.imageset/Contents.json
> +      "scale" : "3x"
![must-badge](https://img.shields.io/badge/review-must-red.svg)

こちらも

```suggestion
```

2022-04-22 06:55 UTC, ykws commented on ios-training/Assets.xcassets/sunny.imageset/Contents.json
> +      "scale" : "3x"
![must-badge](https://img.shields.io/badge/review-must-red.svg)

こちらも

```suggestion
```

2022-04-22 06:55 UTC, ykws commented on ios-training/Weather.swift
> +import Foundation
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

UIKit を import するなら省略可能です。

```suggestion
```

2022-04-22 06:55 UTC, ykws commented on ios-training/Weather.swift
> +protocol Weatherable {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

weather は名詞なので -able とするのは違和感があります。

2022-04-22 06:55 UTC, ykws commented on ios-training/Weather.swift
> +import UIKit
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

UI を表現する部分とドメインを表現する部分が混ざってしまっているので表現が難しくなっていると感じました。
ドメインの表現をまずしてみて、 UI に関する部分は ViewController 側で extension として表現するのはどうでしょうか？

- UI を表現する部分
  - imageName
  - color
- ドメインを表現する部分
  - name

そうすると、以下の懸念も解消できると思います。

> WeatherファイルにUIKitをSunnyモデルなどでUIColorを使いたい都合、importしてしまっていること。

2022-04-22 06:55 UTC, ykws commented on ios-training/Weather.swift
> +    let name: String = "sunny"
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

天気予報のパターンを表現するのに Swift の [Enumarations](https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html) を利用すると、 `switch` とも相性が良く実装漏れを防ぐことができます。

2022-04-22 06:55 UTC, ykws commented on ios-training/WeatherDisplay/WeatherPresenter.swift
> +protocol WeatherPresenterable {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

Presenter も名詞なので、 -able とするのは違和感があります。

Presentable ですかね

2022-04-22 06:55 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +        let fetchedWeather = YumemiWeather.fetchWeather()
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

この UseCase の責務は何になりますか？
単に YumemiWeather の Wrapper であれば、過剰な抽象化の可能性があります。

折角 UseCase を用意するならドメインの処理をここで行なって、 Presenter の責務を軽くしてほしい感じがします。

2022-04-22 06:55 UTC, ykws commented on ios-training/WeatherDisplay/WeatherPresenter.swift
> +    private let weathers: [Weatherable] = [Sunny(), Rainy(), Cloudy()]
![must-badge](https://img.shields.io/badge/review-must-red.svg)

Presenter にドメイン知識が漏れているので、ここで定義するのは避けたいです。

2022-04-22 06:55 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +    // 一旦、同期処理のみ実装しておく
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

protocol のコメントとしては不適切で、実装しているメソッドにあった方が正確です。
どんな実装がされるかは実装側に任せることができるのが protocol の良いところになります。

2022-04-22 07:55 UTC, Reon0429-cat commented on ios-training/WeatherUseCase.swift
> +        let fetchedWeather = YumemiWeather.fetchWeather()
ありがとうございます！ラッパーのつもりで用意したので、Presenterの責務を軽くするように修正しました！

2022-04-22 08:01 UTC, Reon0429-cat commented on ios-training/Weather.swift
> +import UIKit
納得できました！ありがとうございます！

2022-04-22 08:19 UTC, Reon0429-cat commented
@novr @ykws 
修正してみました！
再度ご確認よろしくお願いいたします！

2022-04-26 04:36 UTC, ykws commented on ios-training/Assets.xcassets/cloudy.imageset/Contents.json
> +      "filename" : "iconmonstr-weather-11.pdf",
8fb2a088555904bad97ceee7c6264719cad50ece にて対応できていますね

2022-04-26 04:51 UTC, novr commented on ios-training/WeatherType.swift
> +    var name: String {
[IMO] initの為のコードなのでinit?(String)で書くとよいかと
> `weathers.first(where: { $0.name == fetchedYumemiWeather })`

`guard let weather = WeatherType(fetchedYumemiWeather) else ~`

2022-04-26 04:51 UTC, novr commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +    var imageName: UIImage? {
[IMO] `UIImage`なのでimageNameではないです
imageNameならば、"sunny"などを返して
`weatherImageView.image = UIImage(named: weather.imageName)` となるはず

2022-04-26 04:55 UTC, ykws commented on ios-training/WeatherType.swift
> +    }
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

CaseIterable ではなく、 String を拡張すると case と同じ文字列の定義をしなくても済みます。

2022-04-26 04:55 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        guard let weather = weatherPresenter.fetchWeather() else { return }
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

例外を握り潰してしまっているので、早期に検知できるようにしておくと良いと思います。
とはいえ、現状の API 仕様としては起こり得ないので、 FatalError でも良い感覚です。

2022-04-26 04:55 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +        guard let weather = weathers.first(where: { $0.name == fetchedYumemiWeather }) else {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

enum を以下のように String から変換も可能です。

```suggestion
        guard let weather = WeatherType(rawValue: fetchedYumemiWeather) else {
```

2022-04-26 04:55 UTC, ykws commented on ios-training/WeatherType.swift
> +    }
```suggestion
```

2022-04-26 04:55 UTC, ykws commented on ios-training/WeatherDisplay/WeatherPresenter.swift
> +    func fetchWeather() -> WeatherType?
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

Presentable と WeatherUseCaseProtocol がすごく似ていますが、テストコードを書くためにはどちらも必要になりそうでしょうか？

2022-04-26 04:55 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +private extension WeatherType {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)

UI 向けに拡張されていて良いですね

2022-04-26 04:55 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

ファイル全体で書式が統一されていればどちらでも良いですが、他は空行がないので削除する方向で合わせておきましょうか

```suggestion
```

2022-04-26 05:26 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherPresenter.swift
> +    func fetchWeather() -> WeatherType?
ありがとうございます！
どちらかだけで良い気がしたので、Presenterだけ残しておくことにします！

2022-04-26 06:14 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/104728)

2022-04-27 00:42 UTC, ykws approved these changes
各コメントへの丁寧な対応ありがとうございました！

2022-04-27 01:03 UTC, merged