fetchWeatherをエラーを投げるfetchWeatherに変更し、エラーハンドリングをしました。
Reon0429-cat/ios-training pull request #3
Opened 2022-04-27 01:35 UTC by Reon0429-cat

- 概要
[session3](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Error.md)
'YumemiWeather'がエラーを投げたときのエラーハンドリングの実装

- やったこと
`YumemiWeather.fetchWeather`をエラーを投げる`YumemiWeather.fetchWeather`に変更し、エラーが発生した時にコントローラー側でアラートを表示する処理を実装しました。
`AlertPresentable protocol`のデフォルト実装でエラーをアラートする処理を実装し、`WeatherDisplayViewController`で呼び出しました。

- 動作
iPhone13
https://user-images.githubusercontent.com/66917548/165420313-2569c3fb-b9a7-4853-b0a8-4d8d2007c277.mov

- 気になること
`AlertPresentable protocol`を使って`WeatherDisplayViewController`から切り離したものの、あまり汎用性がないかもしれないこと。

- 備考
なし

2022-04-27 02:28 UTC, novr commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +extension WeatherDisplayViewController: AlertPresentable { }
[IMO]
`protocol AlertPresentable: UIViewController` なので全体的用になっています
個別適用にするには
```
protocol AlertPresentable {
    func presentErrorAlert(title: String)
}

extension AlertPresentable where Self: UIViewController {
    ~
}
```

2022-04-27 02:28 UTC, novr commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        } catch let error as WeatherFetchError {
エラー4分類は何でどんなハンドリングをしていますか？

2022-04-27 02:57 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        } catch let error as WeatherFetchError {
エラー4分類に関して補足です。

[Session3](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Error.md) にリンクがありますが、以下になります。

[Swiftのエラー4分類が素晴らしすぎるのでみんなに知ってほしい](https://qiita.com/koher/items/a7a12e7e18d2bb7d8c77)

2022-04-27 04:29 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        } catch let error as WeatherFetchError {
[こちら](https://qiita.com/koher/items/a7a12e7e18d2bb7d8c77#recoverable-error-%E3%81%AE%E4%BE%8B)のRecoverable errorかなと思いました。do-try-catchを使ってハンドリングしています。

2022-04-27 12:03 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +extension WeatherDisplayViewController: AlertPresentable { }
c57c912560eb7090e745e52fe66a9a3642830720 にて対応済み

2022-04-27 12:10 UTC, ykws requested changes

2022-04-27 12:10 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +            throw WeatherFetchError.notFound
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

この例外が発生するのはどんな時でしょうか？

API の Return Value の仕様は以下です。

> 天気を表す文字列 “sunny” or “cloudy” or “rainy”
>
> https://yumemi-inc.github.io/ios-training/documentation/yumemiweather/yumemiweather/fetchweather(at:)

> [こちら](https://qiita.com/koher/items/a7a12e7e18d2bb7d8c77#recoverable-error-%E3%81%AE%E4%BE%8B)のRecoverable errorかなと思いました。do-try-catchを使ってハンドリングしています。

復旧可能なエラーになりそうでしょうか？

2022-04-27 12:10 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        } catch let error as WeatherFetchError {
> エラーの内容に応じてメッセージを変更する

[YumemiWeatherError](https://yumemi-inc.github.io/ios-training/documentation/yumemiweather/yumemiweathererror/) に対してエラーの内容に応じてメッセージを変更してみてください。

2022-04-28 03:11 UTC, Reon0429-cat commented on ios-training/WeatherUseCase.swift
> +            throw WeatherFetchError.notFound
API側の都合によってアプリケーション側ではどうしようもないので、復旧可能なエラーにならないですね🙇

2022-04-28 09:42 UTC, ykws approved these changes
エラーメッセージの出し分けができているので良いと思いました。

2022-04-28 09:42 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +        } catch let error as YumemiWeatherError {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)

エラーの内容に応じてメッセージを変更できていますね 👍

2022-04-28 09:42 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +    case apiError(YumemiWeatherError)
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)

アプリ側のドメインに組み込めて API 側の変更を UseCase 側に局所化できていて良いですね 👍

2022-04-28 09:42 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +                throw WeatherFetchError.notFound
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

復旧可能ではないので、次の Session で対応しているようにここを fatalError としても良いと思いました。

https://github.com/Reon0429-cat/ios-training/pull/4#discussion_r859741480

2022-04-28 09:42 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +    var errorText: String {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

CustomStringConvertible の protocol に準拠して [description](https://developer.apple.com/documentation/swift/customstringconvertible/1539130-description) を用意する方法もあります。

2022-04-29 13:43 UTC, novr commented on ios-training/WeatherUseCase.swift
> +    var errorText: String {
[LocalizedError](https://developer.apple.com/documentation/foundation/localizederror)のが良いかもしれません

2022-05-06 01:58 UTC, ruby109 commented on ios-training/WeatherUseCase.swift
> +                fatalError("想定外の天気が発生しました。")
fatalErrorの代わりに、ここでは[assertionfailure](https://developer.apple.com/documentation/swift/1539616-assertionfailure)を使った方がいいと思います

2022-05-06 03:02 UTC, Reon0429-cat commented on ios-training/WeatherUseCase.swift
> +                fatalError("想定外の天気が発生しました。")
@ruby109 
ありがとうございます！
issue切ったので後ほど対応してみます！

2022-05-06 03:07 UTC, yumemi-skino approved these changes
LGTM!!

2022-05-06 09:11 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +    var errorText: String {
077d15267d1455cc65eaa2a7f47dc0ff318c27e5 にて対応済み

2022-05-06 09:33 UTC, ruby109 approved these changes
LGTM

2022-05-10 01:01 UTC, merged