fetchWeatherをJsonバージョンにし、最低最高気温を表示させました。
Reon0429-cat/ios-training pull request #4
Opened 2022-04-27 05:44 UTC by Reon0429-cat

- 概要
[session4](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Json.md), [session5](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Codable.md)をまとめてやりました。

- やったこと
`YumemiWeather`の`fetchWeather`をJsonバージョンにし、最低気温と最高気温を表示させました。

- 動作
iPhone13
https://user-images.githubusercontent.com/66917548/165448845-d0ed2468-90ef-415f-8ad4-37d0a7146eb3.mov

- 気になること
特にありません

- 備考
特にありません

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +        let requestData = try encoder.encode(weatherRequest)
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

ここで変換に失敗した場合は WeatherFetchError とはしないですか？

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +        let fetchedJson = try YumemiWeather.fetchWeather(jsonString)
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

こちらもここで変換に失敗するとどのように処理されるでしょうか？

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +        let fetchedJson = try YumemiWeather.fetchWeather(jsonString)
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

ここで取得に失敗した場合は WeatherFetchError とはしないですか？

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +        let fetchedJson = try YumemiWeather.fetchWeather(jsonString)
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

ここで取得に失敗した場合は WeatherFetchError とはしないですか？

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherUseCase.swift
> -            throw WeatherFetchError.notFound
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

`.notFound` は不要になっていますか？

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherUseCase.swift
> -            throw WeatherFetchError.notFound
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

`.notFound` は不要になっていますか？

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +        let weather = try decoder.decode(Weather.self, from: fetchedJsonData)
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

ここで変換に失敗した場合も WeatherFetchError とはしないですか？

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherUseCase.swift
> +        let weather = try decoder.decode(Weather.self, from: fetchedJsonData)
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

ここで変換に失敗した場合も WeatherFetchError とはしないですか？

2022-04-27 12:39 UTC, ykws commented on ios-training/Weather.swift
> +    let weather: String
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

WeatherType も Decodable を適用して扱うこともできます。

```suggestion
    let weather: WeatherType
```

2022-04-27 12:39 UTC, ykws commented on ios-training/Weather.swift
> +    let weather: String
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

WeatherType も Decodable を適用して扱うこともできます。

```suggestion
    let weather: WeatherType
```
```suggestion
    let weather: String
```

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +            fatalError("想定外の天気")
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)

こちらの PR での指摘内容の処理としてこのような形で良いと思います。

https://github.com/Reon0429-cat/ios-training/pull/3#discussion_r859712474

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +            fatalError("想定外の天気")
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)

こちらの PR での指摘内容の処理としてこのような形で良いと思います。

https://github.com/Reon0429-cat/ios-training/pull/3#discussion_r859712474

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +            presentErrorAlert(title: "エラーが発生しました。\(error.errorText)")
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)

こちらの PR での指摘内容でやって欲しいことができています。
WeatherFetchError に対してはこれで良いので、 YumemiWeatherError に対しても同様に扱えると良いです。
対応は Session3 の範囲になります。

https://github.com/Reon0429-cat/ios-training/pull/3#discussion_r859714974

2022-04-27 12:39 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +            presentErrorAlert(title: "エラーが発生しました。\(error.errorText)")
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)

こちらの PR での指摘内容でやって欲しいことが部分的にできていると思います。
WeatherFetchError に対してはこれで良いので、 YumemiWeatherError に対しても同様に扱えると良いです。
対応は Session3 の範囲になります。

https://github.com/Reon0429-cat/ios-training/pull/3#discussion_r859714974

2022-04-28 03:34 UTC, Reon0429-cat commented on ios-training/WeatherUseCase.swift
> -            throw WeatherFetchError.notFound
使われていなかったので、削除しました！

2022-04-28 03:47 UTC, Reon0429-cat commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +            presentErrorAlert(title: "エラーが発生しました。\(error.errorText)")
ViewControllerでYumemiWeatherErrorにerrorをキャストするために、import YumemiWeatherをしないといけないでしょうか？
ViewControllerでYumemiWeatherErrorを識別する方法がまだ理解できていません。

2022-04-28 09:47 UTC, ykws commented on ios-training/WeatherDisplay/WeatherDisplayViewController.swift
> +            presentErrorAlert(title: "エラーが発生しました。\(error.errorText)")
> ViewControllerでYumemiWeatherErrorにerrorをキャストするために、import YumemiWeatherをしないといけないでしょうか？

Yes です

ただ、前の Session で対応してもらっているように UseCase 側でアプリのエラーハンドリングができていると、 Ui 側では import 不要になるし、その方が API に Ui が依存しないので良いです。

https://github.com/Reon0429-cat/ios-training/pull/3#discussion_r860686017

2022-04-28 09:48 UTC, ykws requested changes
rebase してコンフリクトの解消をお願いします！

2022-05-06 09:33 UTC, ykws requested changes
丁寧にエラーを切り分けできていて良いです。

コメントした箇所の do スコープが広すぎるので実際に throw させて挙動を確認してみてください。

2022-05-06 09:33 UTC, ykws commented on ios-training/WeatherUseCase.swift
>          } catch let error as YumemiWeatherError {
この do スコープで throw されるとここで catch されてしまうので、試しに以下の例外を強制的に発生させてどうなるか確認してみて欲しいです。（ guard let の条件をなくして、無条件で throw しても確認可能です）

- throw WeatherFetchError.failedConvertJsonToData
- throw WeatherFetchError.failedDecoding

2022-05-10 01:38 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/142099)

2022-05-10 13:42 UTC, ykws commented on ios-training/WeatherUseCase.swift
>          } catch let error as YumemiWeatherError {
✅ 442b19788d66f4eb604bb537afbf182a327ce9d0

2022-05-10 13:44 UTC, ykws approved these changes
丁寧に対応できていると思いました！

![LGTM](https://image.lgtmoon.dev/20076)

2022-05-11 01:48 UTC, merged